### PR TITLE
Upgrade to Cascalog 2.0 (in progress)

### PR DESCRIPTION
**Pull request by sritchie**
- [x] Upgrade all deps (get to Clojure 1.7.0)
- [x] remove stale docs
- [x] convert def_ops to def_fns
- [x] handle higher order args in the new style
- [x] remove :distinct false, not needed anymore
- [x] add distinct true to queries that need it

### CODE REVIEW

**Comment by eightysteele** [comment]
Boomskies!

**Comment by sritchie** [comment]
Well, lots of test failures, but the whole project compiles!

Next step is to fix all these tests: https://travis-ci.org/wri/forma-clj/builds/70425803

**Comment by sritchie** [comment]
@brookisme and @eightysteele, for the record, this gets us off of ancient Hadoop and up to 1.2.1, which is compatible with what EMR's using.

**Comment by brookisme** [comment]
bacan!

**Comment by eightysteele** [comment]
hadoopskies! @sritchie i'll ping you on chat to sort out namespaces and deprecation stuff...

**Comment by sritchie** [comment]
Looks like we need all this stuff, actually. It's forma-250 that'll let us kill it all!

**Comment by eightysteele** [comment]
#rip

**Pull request closed without merging**
